version: '3.7'

services:
  log-generator:
    image: chentex/random-logger:latest
    container_name: log-generator
    restart: unless-stopped
    environment:
      LOG_LEVEL: "info"

  docker-logs-collector:
    image: logzio/docker-logs-collector:amd64-test  
    container_name: docker-logs-collector
    environment:
      - LOGZIO_LOGS_TOKEN=${LOGZIO_LOGS_TOKEN}
      - OUTPUT_ID=ci-tests
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock  
    depends_on:
      - log-generator
    restart: unless-stopped
    privileged: true
