name: Release

on:
  release:
    types: [created]

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.${{ matrix.architecture }}
          platforms: linux/${{ matrix.architecture }}
          push: true
          tags: |
            logzio/docker-logs-collector-${{ matrix.architecture }}:latest
            logzio/docker-logs-collector-${{ matrix.architecture }}:${{ github.ref_name }}

      - name: Logout from Docker Hub
        if: always()
        run: docker logout
